config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
# from django.views.generic import TemplateView
#from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    #Wagtail urls
    #path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('pages/', include(wagtail_urls)),
    # User management
    path("users/", include("rhs_soccer.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("rhs_soccer.core.urls", namespace="core")),
    path("profiles/", include("rhs_soccer.profiles.urls", namespace="profiles")),
    path("teams/", include("rhs_soccer.teams.urls", namespace="teams")),
    path("matches/", include("rhs_soccer.matches.urls", namespace="matches")),
    path("events/", include("rhs_soccer.events.urls", namespace="events")),
    path("donations/", include("rhs_soccer.payments.urls", namespace="payments")),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

rhs_soccer/core/urls.py
from django.urls import path

from rhs_soccer.core.views import about
from rhs_soccer.core.views import booster
from rhs_soccer.core.views import contact
from rhs_soccer.core.views import home
from rhs_soccer.core.views import privacy
from rhs_soccer.core.views import sponsors
from rhs_soccer.core.views import sponsorship
from rhs_soccer.core.views import terms

app_name = "core"

urlpatterns = [
    path("", home, name="home"),
    path("about/", about, name="about"),
    path("contact/", contact, name="contact"),
    path("terms/", terms, name="terms"),
    path("privacy/", privacy, name="privacy"),
    path("booster/", booster, name="booster"),
    path("sponsors/", sponsors, name="sponsor_page"),
    path("sponsorship/", sponsorship, name="sponsorship"),
    # path("team-page/", team_page, name="team_page"),
    # path("news-page/", news_page, name="news_page"),
    # path("press-releases-page/", press_releases_page, name="press_releases_page"),
    # path("sponsors-page/", sponsors_page, name="sponsors_page"),
]

rhs_soccer/teams/urls.py
from django.urls import path

from rhs_soccer.teams.views import freshman_team
from rhs_soccer.teams.views import jv_team
from rhs_soccer.teams.views import sophomore_team
from rhs_soccer.teams.views import team
from rhs_soccer.teams.views import team_page
from rhs_soccer.teams.views import varsity_team

app_name = "teams"

urlpatterns = [
    path("", team_page, name="team_page"),
    path("team/<uuid:team_id>", team, name="team"),
    path("varsity/", varsity_team, name="varsity"),
    path("jv/", jv_team, name="jv"),
    path("sophomore/", sophomore_team, name="sophomore"),
    path("freshman/", freshman_team, name="freshman"),
]

rhs_soccer/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

rhs_soccer/profiles/models.py
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from tinymce.models import HTMLField
from wagtail.models import Page
from wagtail.admin.panels import FieldPanel, MultiFieldPanel
from wagtail.fields import RichTextField
from wagtail.snippets.models import register_snippet
from modelcluster.models import ClusterableModel


from rhs_soccer.profiles.enums import EmergencyContactRelationship
from rhs_soccer.profiles.enums import PlayerGrade
from rhs_soccer.profiles.enums import PlayerPosition
from rhs_soccer.profiles.enums import PlayerStatus
from rhs_soccer.teams.models import Team
from rhs_soccer.users.enums import UserRoles
from rhs_soccer.users.models import User
from rhs_soccer.utils.common.enums import UsStates


class Profile(Page):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, related_name="profile", null = True)
    phone = PhoneNumberField(_("Phone"), max_length=255, blank=True)
    avatar = models.ForeignKey('wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
        verbose_name=_("Avatar"))
    
    content_panels = Page.content_panels + [
        FieldPanel('user'),
        FieldPanel('phone'),
        FieldPanel('avatar'),
    ]
    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")

    def __str__(self):
        return self.user.get_full_name()

@register_snippet
class Address(models.Model):
    address = models.CharField(max_length=255, verbose_name=_("Address"))
    address2 = models.CharField(
        max_length=255,
        verbose_name=_("Address 2"),
        blank=True,
    )
    city = models.CharField(max_length=255, verbose_name=_("City"))
    state = models.CharField(
        max_length=255,
        verbose_name=_("State"),
        choices=UsStates.choices(),
        default=UsStates.MINNESOTA.value,
    )
    zip_code = models.CharField(max_length=255, verbose_name=_("Zip Code"))
    panels = [
        FieldPanel('address'),
        FieldPanel('address2'),
        FieldPanel('city'),
        FieldPanel('state'),
        FieldPanel('zip_code'),

    ]
    class Meta:
        verbose_name = _("Address")
        verbose_name_plural = _("Addresses")

    def __str__(self) -> str:
        return self.address

@register_snippet
class Player(ClusterableModel):
    uuid = models.UUIDField(_("UUID"), default=uuid.uuid4, editable=False, unique=True)
    team = models.ForeignKey(
        Team,
        on_delete=models.SET_NULL,
        related_name="players",
        blank=True,
        null=True,
    )
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE, related_name="player")
    jeresy_number = models.CharField(_("Jeresy Number"), blank=True, max_length=10)
    grade = models.CharField(
        _("Grade"),
        choices=PlayerGrade.choices(),
        blank=True,
        help_text=_("Grade"),
        max_length=2,
    )
    position = models.CharField(
        _("Position"),
        max_length=255,
        blank=True,
        choices=PlayerPosition.choices(),
    )
    height = models.CharField(
        _("Height"),
        max_length=255,
        blank=True,
    )
    weight = models.CharField(
        _("Weight"),
        max_length=255,
        blank=True,
    )
    status = models.CharField(
        max_length=255,
        choices=PlayerStatus.choices(),
        verbose_name=_("Status"),
        blank=True,
        help_text=_("Status"),
    )
    bio = RichTextField(
        _("Bio"),
        blank=True,
    )
    is_published = models.BooleanField(_("Published"), default=False)
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    panels = [
        FieldPanel('uuid'),
        FieldPanel('team'),
        FieldPanel('profile'),
        FieldPanel('jersey_number'),
        FieldPanel('grade'),
        FieldPanel('position'),
        FieldPanel('height'),
        FieldPanel('weight'),
        FieldPanel('status'),
        FieldPanel('bio'),
        FieldPanel('is_published'),
    ]
    class Meta:
        verbose_name = _("Player")
        verbose_name_plural = _("Players")

    def __str__(self):
        return self.profile.user.get_full_name()

    def get_avatar(self):
        return self.profile.avatar

    get_avatar.short_description = _("Avatar")

    def get_short_name(self):
        return self.profile.user.get_short_name()

@register_snippet
class Parent(ClusterableModel):
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE, related_name="parent")
    players = models.ManyToManyField(Player, related_name="parents", blank=True)
    address = models.ForeignKey(
        Address,
        on_delete=models.SET_NULL,
        related_name="parents",
        blank=True,
        null=True,
    )
    emergency_contact_name = models.CharField(
        _("Emergency Contact Name"),
        max_length=50,
        blank=True,
    )
    emergency_contact_phone = PhoneNumberField(
        _("Emergency Contact Phone"),
        max_length=20,
        blank=True,
    )
    emergency_contact_relationship = models.CharField(
        _("Emergency Contact Relationship"),
        max_length=50,
        blank=True,
        choices=EmergencyContactRelationship.choices(),
        default=EmergencyContactRelationship.OTHER.value,
    )
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    panels = [
        FieldPanel('profile'),
        FieldPanel('players'),
        FieldPanel('address'),
        FieldPanel('emergency_contact_name'),
        FieldPanel('emergency_contact_phone'),
        FieldPanel('emergency_contact_relationship'),
        FieldPanel('created_at'),
        FieldPanel('updated_at'),
    ]

    class Meta:
        verbose_name = _("Parent")
        verbose_name_plural = _("Parents")

    def __str__(self):
        return self.profile.get_full_name()

    def get_full_name(self):
        return self.profile.get_full_name()

    get_full_name.short_description = _("Full Name")

@register_snippet
class Coach(models.Model):
    uuid = models.UUIDField(_("UUID"), default=uuid.uuid4, editable=False, unique=True)
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE, related_name="coach")
    address = models.ForeignKey(
        Address,
        on_delete=models.SET_NULL,
        related_name="coaches",
        blank=True,
        null=True,
    )
    bio = RichTextField(_("Bio"), blank=True)
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    panels = [
        FieldPanel('uuid'),
        FieldPanel('profile'),
        FieldPanel('address'),
        FieldPanel('bio'),
        FieldPanel('created_at'),
        FieldPanel('updated_at'),
    ]
    class Meta:
        verbose_name = _("Coach")
        verbose_name_plural = _("Coaches")

    def __str__(self):
        return self.profile.get_full_name()

    def get_full_name(self):
        return self.profile.get_full_name()

    get_full_name.short_description = _("Full Name")

@register_snippet
class Manager(models.Model):
    uuid = models.UUIDField(_("UUID"), default=uuid.uuid4, editable=False, unique=True)
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE, related_name="manager")
    address = models.ForeignKey(
        Address,
        on_delete=models.SET_NULL,
        related_name="managers",
        blank=True,
        null=True,
    )
    bio = RichTextField(_("Bio"), blank=True)
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    panels = [
        FieldPanel('uuid'),
        FieldPanel('profile'),
        FieldPanel('address'),
        FieldPanel('bio'),
        FieldPanel('created_at'),
        FieldPanel('updated_at'),


    ]
    class Meta:
        verbose_name = _("Manager")
        verbose_name_plural = _("Managers")

    def __str__(self):
        return self.user.get_full_name()

    def get_full_name(self):
        return self.user.get_full_name()

    get_full_name.short_description = _("Full Name")

rhs_soccer/events/forms/volunteer.py
from django import forms

from rhs_soccer.events.models import Volunteer


class VolunteerForm(forms.ModelForm):
    class Meta:
        model = Volunteer
        fields = ["event", "user"]
        widgets = {
            "event": forms.HiddenInput(),
            "user": forms.HiddenInput(),
        }
        labels = {
            "event": "Event",
            "user": "User",
        }

rhs_soccer/core/views.py
from django.shortcuts import render

from rhs_soccer.core.forms.contact import ContactForm
from rhs_soccer.core.forms.sponsor_application import SponsorshipApplicationForm
from rhs_soccer.core.models import AboutPage
from rhs_soccer.core.models import ContactPage
from rhs_soccer.core.models import PrivacyPolicyPage
from rhs_soccer.core.models import Sponsor
from rhs_soccer.core.models import SponsorPage
from rhs_soccer.core.models import SponsorshipPackage
from rhs_soccer.core.models import TermsOfServicePage
from rhs_soccer.teams.models import Team


def home(request):
    title = "Home of the Irish"
    about_page = AboutPage.objects.first()
    teams = Team.objects.filter(home_team=True)
    sponsors = Sponsor.objects.filter(level="Platinum").order_by("?")[:5].all()
    contact_form = ContactForm()

    context = {
        "title": title,
        "about_page": about_page,
        "teams": teams,
        "sponsors": sponsors,
        "contact_form": contact_form,
    }
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            context["success"] = True
            context["contact_form"] = ContactForm()
            return render(request, "core/home.html", context)
        context["contact_form"] = form
    return render(request, "core/home.html", context)


def about(request):
    about_page = AboutPage.objects.first()
    sponsors = Sponsor.objects.all()
    context = {
        "about_page": about_page,
        "sponsors": sponsors,
        "title": about_page.title,
    }
    return render(request, "core/about.html", context)


def contact(request):
    contact_page = ContactPage.objects.first()
    if contact_page is None:
        contact_page = ContactPage()
    context = {
        "contact_page": contact_page,
        "title": contact_page.title,
        "subtitle": contact_page.subtitle,
        "contact_form": ContactForm(),
    }
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            context["success"] = True
            context["contact_form"] = ContactForm()
            return render(request, "core/contact.html", context)
        context["contact_form"] = form
    return render(request, "core/contact.html", context)


def sponsors(request):
    sponsors = Sponsor.objects.all()
    sponsor_page = SponsorPage.objects.first()
    context = {
        "sponsors": sponsors,
        "sponsor_page": sponsor_page,
        "title": "Sponsors",
    }
    return render(request, "core/sponsors.html", context)


def sponsorship(request):
    packages = SponsorshipPackage.objects.all()
    application_form = SponsorshipApplicationForm()
    context = {
        "packages": packages,
        "application_form": application_form,
        "title": "Sponsorship",
    }
    if request.method == "POST":
        form = SponsorshipApplicationForm(request.POST)
        if form.is_valid():
            form.save()
            context["success"] = True
            context["application_form"] = SponsorshipApplicationForm()
            return render(request, "core/sponsorships.html", context)
        context["application_form"] = form
    return render(request, "core/sponsorships.html", context)


def terms(request):
    terms_page = TermsOfServicePage.objects.first()
    context = {
        "terms_page": terms_page,
        "title": terms_page.title,
        "subtitle": terms_page.subtitle,
    }
    return render(request, "core/terms.html", context)


def privacy(request):
    privacy_page = PrivacyPolicyPage.objects.first()
    context = {
        "privacy_page": privacy_page,
        "title": privacy_page.title,
        "subtitle": privacy_page.subtitle,
    }
    return render(request, "core/privacy.html", context)


def booster(request):
    # booster_page = BoosterPage.objects.first()
    # context = {
    #     "booster_page": booster_page,
    #     "title": booster_page.title,
    #     "subtitle": booster_page.subtitle,
    #     "officers": BoosterOfficer.objects.filter(page=booster_page),
    # }
    return render(request, "core/booster.html")

rhs_soccer/templates/profiles/includes/donation.html
{% load static %}
{% load solo_tags %}
{% get_solo 'core.SiteSettings' as site_settings %}

<div class="rainbow-callto-action clltoaction-style-player style-3">
    <div class="row row--0 align-items-center content-wrapper">
        <div class="col-lg-8">
            <div class="inner">
                <div class="content text-left">
                    <h3 class="title" data-sal="slide-up" data-sal-duration="400" data-sal-delay="200">Would you help {{ player.profile.user.first_name }}'s Team
                        {% if site_settings.fund_raising_mode %}
                        reach their fund raising goal
                        {% endif %}?
                        </h3>
                    {% if site_settings.fund_raising_mode  %}
                    {% include 'profiles/includes/goal_progress.html' %}
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="call-to-btn text-start text-lg-end" data-sal="slide-up" data-sal-duration="400" data-sal-delay="400">
                <a class="btn-default" href="#">
                    DONATE
                </a>
            </div>
        </div>
    </div>
</div>

rhs_soccer/templates/profiles/includes/goal_progress.html
{% load i18n humanize %}
<div class="single-progress large-size  no-radius">
    <h6 class="title">{{ player.profile.user.first_name }} Team's Progress</h6>
    <p>$<strong>{{ raised|intcomma  }}</strong> raised of $<strong>{{ goal|intcomma }}</strong> team goal</p>
    <div class="progress">
        <div class="progress-bar wow fadeInLeft" data-wow-duration="0.5s" data-wow-delay=".3s" role="progressbar" style="width: {{ percentage  }}%" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100">
        </div>
        {% comment %} <span class="progress-number"><strong>{{ percentage|floatformat:0|intcomma }}</strong>%</span> {% endcomment %}
    </div>
</div>

rhs_soccer/templates/profiles/includes/player.html
{% load static %}

<div class="rainbow-portfolio-details rainbow-section-gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 offset-lg-1">
                <div class="inner">
                    <div class="details-list">
                        <div class="thumbnail player_image"><img class="radius w-100" src="
                            {% if player.get_avatar %}
                                {{ player.get_avatar.url }}
                            {% else %}
                                {% static 'images/defaults/profile_pic_default_1055x1050.png' %}
                            {% endif %}" alt="{{ player.user.first_name }}' image
                            "></div>
                        <div class="row mt--40 row--30">
                            <div class="col-lg-6">
                                <div class="content-left">
                                    <h4 class="title">{{ player.get_full_name}}</h4>
                                    <div class="single-list-wrapper">
                                        <div class="single-list"><label>Position:</label><span>
                                            {{ player.position }}
                                        </div>
                                        <div class="single-list"><label>Jersey Number:</label><span>
                                            {{ player.jeresy_number }}
                                        </span></div>
                                        <div class="single-list">
                                            <label>Season:</label><span>
                                                {{ player.team.season }}
                                            </span>
                                        </div>
                                        <div class="single-list">
                                            <label>Grade:</label><span>
                                                {{ player.grade }}
                                            </span>
                                        </div>
                                        <div class="single-list">
                                            <label>Status:</label><span>
                                                {{ player.status }}
                                            </span>
                                        </div>
                                        <div class="single-list">
                                            <label>Team:</label><span>
                                                {{ player.team.short_name }}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 mt_md--30 mt_sm--30">
                                <div class="content-right">
                                    <h5 class="subtitle">About {{ player.profile.user.first_name }}</h5>
                                    <div class="description">
                                        <p>{{ player.bio|safe }}
                                        </p>
                                    </div>
                                    <div class="description">
                                        {% if player.team.fundraiser %}
                                        {% include 'profiles/includes/donation.html' %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

rhs_soccer/templates/profiles/includes/players.html
{% load static %}
<div class="rainbow-team-area rainbow-section-gap">
    <div class="wrapper plr--65">
        <div class="row mb--20">
            <div class="col-lg-12">
                <div class="section-title text-center" data-sal="slide-up" data-sal-duration="700" data-sal-delay="150">
                    <h4 class="subtitle "><span class="theme-gradient">Players.</span></h4>
                    <h2 class="title w-600 mb--20">Our Players</h2>
                </div>
            </div>
        </div>
        <div class="row row--15">
            {% if players %}
            {% for player in players %}
            <div class="col-lg-3 col-md-6 col-sm-6 col-12 mt--30" data-sal="slide-up" data-sal-duration="700">
                <div class="rainbow-team team-style-three">
                    <div class="inner">
                        <a href="{% url 'profiles:player' player.id %}">
                            <div class="thumbnail"><img src="
                                {% if player.profile.avatar %}
                                {{ player.profile.avatar.url }}
                                {% else %}
                                {% static 'images/defaults/profile_pic_default_1055x1050.png' %}
                                {% endif %}
                                " alt="{{ player.profile.get_full_name }} avatar">
                            </div>
                        </a>
                        <div class="content">
                            <div class="team-info">
                                <h2 class="title">
                                        {{ player.profile.user.get_full_name }}
                                </h2>
                                <h6 class="subtitle theme-gradient">
                                        {{ player.position }}
                                </h6>
                                <div class="team-form"><span class="location">{{ player.team.short_name}}</span></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="col-lg-12">
                <div class="section-title text-center" data-sal="slide-up" data-sal-duration="700" data-sal-delay="150">
                    <h4 class="subtitle "><span class="theme-gradient">Players.</span></h4>
                    <h2 class="title w-600 mb--20">No Players Found</h2>
                </div>
            {% endif %}
        </div>
    </div>
</div>